In [4]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [5]:
train_data = pd.read_csv('data.csv')

# 1. Assign the data to predictor and outcome variables

##### note1: reshape(-1,1): if the data has a single feature/column
##### note2: reshape(1,-1): if the data has a single sample


In [12]:
X = train_data['Var_X'].values.reshape(-1,1)
X

array([[-0.33532],
       [ 0.0216 ],
       [-1.19438],
       [-0.65046],
       [-0.28001],
       [ 1.93258],
       [ 1.2262 ],
       [ 0.74727],
       [ 3.32853],
       [ 2.87457],
       [-1.48662],
       [ 0.37629],
       [ 1.43918],
       [ 0.24183],
       [-2.7914 ],
       [ 1.08176],
       [ 2.81555],
       [ 0.54924],
       [ 2.36449],
       [-1.01925]])

In [19]:
y = train_data['Var_Y'].values.reshape(-1,1)
y

array([[  6.66854],
       [  3.86398],
       [  5.16161],
       [  8.43823],
       [  5.57201],
       [-11.1327 ],
       [ -5.31226],
       [ -4.63725],
       [  3.8065 ],
       [ -6.06084],
       [  7.22328],
       [  2.38887],
       [ -7.13415],
       [  2.00412],
       [  4.29794],
       [ -5.86553],
       [ -5.20711],
       [ -3.52863],
       [-10.16202],
       [  5.31123]])

# 2. Create polynomial features
# TODO: Create a PolynomialFeatures object, then fit and transform the
# predictor feature

In [22]:
poly_feature = PolynomialFeatures(degree=1)

In [18]:
X_poly = poly_feature.fit_transform(X)
X_poly

array([[ 1.00000000e+00, -3.35320000e-01,  1.12439502e-01,
        -3.77032139e-02,  1.26426417e-02],
       [ 1.00000000e+00,  2.16000000e-02,  4.66560000e-04,
         1.00776960e-05,  2.17678234e-07],
       [ 1.00000000e+00, -1.19438000e+00,  1.42654358e+00,
        -1.70383513e+00,  2.03502660e+00],
       [ 1.00000000e+00, -6.50460000e-01,  4.23098212e-01,
        -2.75208463e-01,  1.79012097e-01],
       [ 1.00000000e+00, -2.80010000e-01,  7.84056001e-02,
        -2.19543521e-02,  6.14743813e-03],
       [ 1.00000000e+00,  1.93258000e+00,  3.73486546e+00,
         7.21792628e+00,  1.39492200e+01],
       [ 1.00000000e+00,  1.22620000e+00,  1.50356644e+00,
         1.84367317e+00,  2.26071204e+00],
       [ 1.00000000e+00,  7.47270000e-01,  5.58412453e-01,
         4.17284874e-01,  3.11824468e-01],
       [ 1.00000000e+00,  3.32853000e+00,  1.10791120e+01,
         3.68771565e+01,  1.22746722e+02],
       [ 1.00000000e+00,  2.87457000e+00,  8.26315268e+00,
         2.37530108e+01

# 3. Make and fit the polynomial regression model
# TODO: Create a LinearRegression object and fit it to the polynomial predictor features

In [20]:
poly_model = LinearRegression(fit_intercept = False).fit(X_poly, y)

In [21]:
poly_model

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=False)