In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('data.csv',header=None)
data

0        1  2
0   0.245390  0.81725  0
1   0.217740  0.76462  0
2   0.201610  0.69737  0
3   0.201610  0.58041  0
4   0.247700  0.49561  0
..       ...      ... ..
91  0.155530  0.13596  1
92  0.238480  0.12427  1
93  0.330650  0.12427  1
94  0.095622  0.26170  1
95  0.091014  0.20322  1

[96 rows x 3 columns]

In [3]:
x_values = np.asarray(data.iloc[:,:-1])
x_values 

array([[0.24539 , 0.81725 ],
       [0.21774 , 0.76462 ],
       [0.20161 , 0.69737 ],
       [0.20161 , 0.58041 ],
       [0.2477  , 0.49561 ],
       [0.32834 , 0.44883 ],
       [0.39516 , 0.48099 ],
       [0.39286 , 0.57164 ],
       [0.33525 , 0.62135 ],
       [0.33986 , 0.71199 ],
       [0.34447 , 0.81433 ],
       [0.28226 , 0.82602 ],
       [0.26613 , 0.75    ],
       [0.26613 , 0.63596 ],
       [0.32604 , 0.54825 ],
       [0.28917 , 0.65643 ],
       [0.80069 , 0.71491 ],
       [0.80069 , 0.64181 ],
       [0.80069 , 0.50146 ],
       [0.79839 , 0.36988 ],
       [0.73157 , 0.25    ],
       [0.63249 , 0.18275 ],
       [0.60023 , 0.27047 ],
       [0.66014 , 0.34649 ],
       [0.70161 , 0.42251 ],
       [0.70853 , 0.53947 ],
       [0.71544 , 0.63304 ],
       [0.74309 , 0.72076 ],
       [0.75    , 0.63596 ],
       [0.75    , 0.46345 ],
       [0.72235 , 0.35526 ],
       [0.66935 , 0.28509 ],
       [0.20622 , 0.94298 ],
       [0.26613 , 0.8962  ],
       [0.3813

In [4]:
Y_values = np.asarray(data.iloc[:,-1])
Y_values 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

# TODO: Create the decision tree model and assign it to the variable model.

In [5]:
model = DecisionTreeClassifier()

# TODO: Fit the model.

In [6]:
model.fit(x_values, Y_values)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

# TODO: Make predictions. Store them in the variable y_pred.

In [8]:
y_pred = model.predict(x_values)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

# Calculate the accuracy and assign it to the variable acc.

In [11]:
acc = accuracy_score(Y_values,y_pred)
acc

1.0